FROM python:3.10-slim

WORKDIR /app

COPY server/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY server/ .
COPY shared/ ./shared/
COPY trust/ ./trust/

CMD ["python", "server.py"]
